foo/config/routes.rb
Rails.application.routes.draw do
  resources :albums
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'pages#landing'
  get '/api' => 'api#example'
end

foo/app/models/album.rb
class Album < ApplicationRecord
end

foo/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

foo/app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :set_album, only: [:show, :edit, :update, :destroy]

  # GET /albums
  # GET /albums.json
  def index
    @albums = Album.all
  end

  # GET /albums/1
  # GET /albums/1.json
  def show
  end

  # GET /albums/new
  def new
    @album = Album.new
  end

  # GET /albums/1/edit
  def edit
  end

  # POST /albums
  # POST /albums.json
  def create
    @album = Album.new(album_params)

    respond_to do |format|
      if @album.save
        format.html { redirect_to @album, notice: 'Album was successfully created.' }
        format.json { render :show, status: :created, location: @album }
      else
        format.html { render :new }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /albums/1
  # PATCH/PUT /albums/1.json
  def update
    respond_to do |format|
      if @album.update(album_params)
        format.html { redirect_to @album, notice: 'Album was successfully updated.' }
        format.json { render :show, status: :ok, location: @album }
      else
        format.html { render :edit }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /albums/1
  # DELETE /albums/1.json
  def destroy
    @album.destroy
    respond_to do |format|
      format.html { redirect_to albums_url, notice: 'Album was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_album
      @album = Album.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def album_params
      params.require(:album).permit(:title)
    end
end

foo/app/controllers/api_controller.rb
class ApiController < ApplicationController

  def example
    render json: {foo: 'bar'}
  end
end

foo/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

foo/app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def landing
  end

end

foo/app/helpers/albums_helper.rb
module AlbumsHelper
end

foo/app/helpers/application_helper.rb
module ApplicationHelper
end

foo/app/views/albums/_form.html.erb
<%= form_with(model: album, local: true) do |form| %>
  <% if album.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(album.errors.count, "error") %> prohibited this album from being saved:</h2>

      <ul>
      <% album.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :album_title %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

foo/app/views/albums/edit.html.erb
<h1>Editing Album</h1>

<%= render 'form', album: @album %>

<%= link_to 'Show', @album %> |
<%= link_to 'Back', albums_path %>

foo/app/views/albums/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Albums</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @albums.each do |album| %>
      <tr>
        <td><%= album.title %></td>
        <td><%= link_to 'Show', album %></td>
        <td><%= link_to 'Edit', edit_album_path(album) %></td>
        <td><%= link_to 'Destroy', album, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Album', new_album_path %>

foo/app/views/albums/new.html.erb
<h1>New Album</h1>

<%= render 'form', album: @album %>

<%= link_to 'Back', albums_path %>

foo/app/views/albums/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @album.title %>
</p>

<%= link_to 'Edit', edit_album_path(@album) %> |
<%= link_to 'Back', albums_path %>

foo/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Foo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

foo/app/views/pages/landing.erb
<h1>Welcome to <%= Rails.application.class.parent_name %></h1>